### ISSUE TITLE
Backwards compatibility with Zabbix 2.2 possibly broken

### ISSUE THREAD

**Issue by velinath** [velinath/zabbixweb#19]
Per blog commenter Edur: 

Hi, nice work!

I checked out the last revision on github. But the meters does not work, the font only works after I add “” to the header and the RAM values are wrong calculated i think (ex. shows -4G / 16G). I have an zabbix server v2.2. Have you an working copy like your Screenshot? :)

Thanks a lot.

**Comment by eburgueno** [comment]
I think it depends on the vm.memory.size[*] items you have set up for your hosts. There are [many](https://www.zabbix.com/documentation/2.4/manual/appendix/items/vm.memory.size_params) possible, we are only using a few for our math. I wonder if we need to make this more generic so that it works on all OS, but we will always need to advise the user what items we require.

**Comment by velinath** [comment]
Could be that he doesn't have the proper values configured per our readme, I'll check back with him on the blog.

**Comment by vicendominguez** [comment]
:warning: I can reproduce this issue on Zabbix 2.2.9 using this items to get the mem info:

  * vm.memory.size[available]
  * vm.memory.size[total]

**Comment by velinath** [comment]
@vicendominguez does it work if you configure memory items per our readme?

**Comment by vicendominguez** [comment]
I think it will work, but I cannot check it now... 

Perhaps this topic a little [FUD](http://en.wikipedia.org/wiki/Fear,_uncertainty_and_doubt) but, why to check `free` memory and not `available`?? It would be interesting to know for my understanding.....

The original Zabbix Linux template is checking `available` key (it has a trigger too), at least in Zbx 2.2.x.

**Comment by velinath** [comment]
I believe the reason we do things this way is because Windows and Linux servers report memory usage in different values. Zabbix 2.5 also made a breaking change to the way memory is reported if I recall correctly.

Check out #6 for more details on this particular issue.

**Comment by eburgueno** [comment]
@vicendominguez RedHat and CentOS 6 do not have "available" memory, among others. So Zabbix has no way of reporting it. This is [depends on the kernel version](http://blog.famzah.net/2014/09/24/memavailable-metric-for-linux-kernels-before-3-14-in-procmeminfo/).
Defining what is available vs "free" memory is a somewhat subjective thing, and hard to make the same in different OSs. I consider Free memory the sum of 'free' and 'cached' values on a pre-3.14 Linux kernel, because applications can reclaim cached memory immediately. The kernel devs have a different (but possibly) more accurate approach.

**Comment by vicendominguez** [comment]
Thx for the answers guys and for your work.

I have about 40 Centos 6.x without issues with the ` available`  memory. It is easy to change that key in the index.html.... i prefer to choose the ` available`  value. 

:+1:

**Comment by velinath** [comment]
Sounds like this issue is resolved as it appears to be down to end user preference. Closing this ticket out.
