### ISSUE TITLE
CPU Usage set to values above 100%

### ISSUE THREAD

**Issue by ssgrasshopper** [velinath/zabbixweb#21]
Hi Guys

I am having issues with CPU usage graphs showing values more than 100%. I have added the following into the Template Windows OS with the following scenarios with the same outcome.

Version: Zabbix 2.4.5

Set 1:

-system.cpu.num[online]
-Zabbix Agent Active
-numeric unsigned
-decimal

Set 2:

-system.cpu.num
-Zabbix Agent
-numeric unsigned
-decimal

Any ideas? Not sure if this is a dumb end user issue or a config bug.

Cheers
R

**Comment by velinath** [comment]
I think this might actually be a problem with the way Zabbix does its reporting - I've observed this in my setup here as well.

There's a discussion on my original blog post that talks about this - I'll paste some relevant stuff here:

Basically, if Zabbix doesn’t know how many cores are actually in the system or doesn’t report that information, the dashboard won’t have enough information to properly parse the load on the server. Best bet? Make sure that all your systems are reporting the number of cores in their inventories.

I'll leave this open for now but there may not be anything that we can do.

**Comment by eburgueno** [comment]
CPU is a tricky one.

Zabbix can monitor **CPU Load** and **CPU Utilization**. The full list of supported items is [here](https://www.zabbix.com/documentation/2.4/manual/config/items/itemtypes/zabbix_agent). From there we get:

* `system.cpu.load[<cpu>,<mode>]`, where
 * possible values for `<cpu>` are `all` (default) or `percpu` (total load divided by online CPU count). `percpu` is supported since Zabbix 2.0.0.
 * possible values for `<mode>` are `avg1` (one-minute average, default), `avg5` or `avg15`.

and

* `system.cpu.num[<type>]`, where
 * possible values for `<type>` are `online` (default) or `max`.

The way we calculate it for the dashboard is pre-2.0: We require Zabbix to know how many CPU cores are available on the server (item: `system.cpu.num`), then we divide the `system.cpu.load` of all CPUs by this number. This should give you a value between 0.01 and 1 when the load on the server is less than the number of available cores, and higher than 1 when the server is overloaded. 

There are two problems with this approach:
1. We assume/require that the servers have these two items associated with them: `system.cpu.num` and `system.cpu.load`. Any optional arguments (between the square brackets) and we wouldn't match it on our code (lines [216](https://github.com/velinath/zabbixweb/blob/master/index.html#L216) and [219](https://github.com/velinath/zabbixweb/blob/master/index.html#L219)), because we don't do substring matching (except for filesystems).
2. We calculate the average load per CPU ourselves by requiring `system.cpu.num`, instead of letting Zabbix do this by itself with `system.cpu.load[percpu]`. Different sites will have different configs for this item. Mine migrated from version 1.8 where `percpu` was not available so I configured it manually. Newer deployments might have gone for a different route.

We could change the code to account for all possibilities. It just means adding more `if`s (or `case`s). We could also add a user-configurable option in the preferences but I would be against this because it's complexity we don't need to present the user with.

@ssgrasshopper Can you please confirm from the above which items are your servers assigned? Could you also show us what the 'Latest Data' section shows for one of your servers?

**Comment by velinath** [comment]
Maybe we could do something like 

```javascript
case 'system.cpu.load[percpu]':
            	    var e = 'system.cpu.num';
            	    thisHostObj.items = $.grep(thisHostObj.items, function(e) {
            	    	return e.key_ != key_;
            	    });
            	    e = 'system.cpu.load';
            	    thisHostObj.items = $.grep(thisHostObj.items, function(e) {
            	    	return e.key_ != key_;
            	    });
            	    thisHostObj.avgCpuLoad = $(this)[0].lastvalue;
            	    break;
```

We'd need some logic later on the page to check to see if avgCpuLoad is set, or set a flag, or something, but I think that would work.

**Comment by heyvoon** [comment]
Zabbix 2.x has...

![2016-03-17_15-28-17](https://cloud.githubusercontent.com/assets/3281265/13849116/01799ec2-ec55-11e5-8e51-f89b35c4ae1c.jpg)

that calculates CPU utilization. Why not use this key?
