### ISSUE TITLE
Add view customization for end user

### ISSUE THREAD

**Issue by velinath** [velinath/zabbixweb#5]
I think it's just a matter of writing regex to pick out the name of the interface. Some of these are gonna be long (like, on Windows systems, it'll return crap like "Broadcom Network Card RN-2902-B \#2", so I'm thinking not display them, but at least break them up and delineate somehow.

Probably, I'll move all the network traffic inside a dropdown like the way Disks is done.

**Comment by velinath** [comment]
Ok. I've got the beginnings of the modal cobbled together. Does this look usable to you or were you thinking something else?

**Comment by eburgueno** [comment]
I think it looks good. I thought about a couple other options I'd like to see, but got distracted with fixing #8.
Of the top of my head:
* Allow the user to specify a Host Group to list, instead of all hosts by default ("groupids" on the host.get call)
* Allow alternating between col-md-2 and col-md-3 for the server grid. I have a very high resolution in my monitor, and just 4 columns wastes a lot of space.
* Maybe let the user specify the threshold for the warning/alert on disk space.

The more options we add, the more complex the code, so unless you want to take this into a full blown "visualization engine" direction we don't need to get too crazy. I wouldn't mind either way :)

**Comment by derekcat** [comment]
"Allow the user to specify a Host Group to list, instead of all hosts by default ("groupids" on the host.get call)"
Or rather, select Hosts groups to list.  
I just spent a little while figuring out how to exclude some hosts from my instance of your GUI, as we had twice as many switch hosts as server hosts, so it was very hard to glance at.

Inside $.each(hosts, function() {
I added:
        if (thisHostObj.name.match(/Switch/) || thisHostObj.name.match(/TemPageR/)) { //successfully matches all switches, and TemPageRs
                return null; // This kills the array element
        }

Also, I'm not sure where to mention or put them, but I wrote a few lines that will supply OS versions for Mac OS 10.6-11, and "Ubuntu" (it looks like Ubuntu's uname -a doesn't provide a clear distinction for Ubuntu's versions).  Also on this note, the Linux label for the OS doesn't work for me, for Cent6/7/Ubuntu..
Sorry - very new to GitHub ^_^"  Could you point me at the right place for that?

**Comment by derekcat** [comment]
Eburgueno, you're awesome!
I love it!  It's a lot slicker than my if and nullify.  I implemented it on my server, created a group with my OS templates and the current hosts (hopefully that will automagically add them).

> Also, is generally a bad idea to use the 'name' field for anything. Is not portable, and other users can name things differently than what we expect (see #4 for example).

It had occurred to me that "Switches" was not the most reliable way of determining what to exclude...  Perhaps filtering by Zabbix-Agent vs SNMP would be a more general solution?  Though I can see some people using SNMP to monitor servers instead of the agent.

> The best way to contribute to a git project is to fork the repo, commit your changes to your copy, and then creating a pull request.

Done!  Thanks!  ^_^  I was under the impression that it was more Wiki-style, but that makes a lot more sense for code.  I added a few comments, a commented version of the groupids line, and the Ubuntu/Mac OS lines, and created a pull request.  (I like to be very verbose for clarity).  On that note, I created a wiki page on velinath/zabbixweb so that it's a bit more clear how to install.

> In my case, my Zabbix instance has an item with key "system.hostname" populating the OS Full field, not the OS one.

Ahh, that's why.  I wasn't reading the key name carefully down there.  All of our hostnames are just names, no OSes.  It occurs to me now, that perhaps we should have a line at the end of the OSes to match just Linux, for the os key?  Just as a catchall for other distros.

**Comment by velinath** [comment]
I think we actually do have a catchall for the OS key:

```
 else if (thisHostObj.inventory.os_full) {
if(thisHostObj.inventory.os_full.indexOf('Linux') > -1) {
thisHostObj.os = 'Linux';
}
} else {
thisHostObj.os = 'OS Unavailable';
}
```

in index.html, unless I'm misconstruing what you're saying.

**Comment by derekcat** [comment]
Hey Velinath, 
My thought was to have a "Linux" check for thisHostObj.inventory.os instead of thisHostObj.inventory.os_full, as the defaults for Zabbix don't fill os_full.  Say, setting the name to 'Generic Linux'

Eburgueno's comment in #11 would be a good solution too.  (Really, Zabbix-Agent should be the one figuring out what the OS is, and filling Inventory cleanly). :)

**Comment by velinath** [comment]
I've got the "network dropdown" as a toggle in the settings menu (just a mockup for now), and I think we knocked out all the rest of the issues here. Any objections to closing out this issue and covering things in #13 as they come up?

**Comment by eburgueno** [comment]
Should we close this one once we have the settings taking effect? or should we open another issue to track that? I don't mind either way.

**Comment by velinath** [comment]
Let's track settings functionality on #13.

Closing this one out.
